-- Production schema for the QR + scale ingestion service.
create extension if not exists pgcrypto;

create table if not exists public.devices (
  id text primary key,
  name text,
  active boolean not null default true,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.rolls (
  qr_code text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.roll_scale_secrets (
    name text primary key,
    encrypted_value text not null,
    updated_at timestamptz not null default now(),
    constraint roll_scale_secrets_name_format
        check (name ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'),
    constraint roll_scale_secrets_value_length
        check (length(encrypted_value) between 1 and 16384)
);

alter table public.roll_scale_secrets enable row level security;
revoke all on table public.roll_scale_secrets from anon, authenticated;
grant all on table public.roll_scale_secrets to service_role;

create table if not exists public.measurements (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  qr_code text not null,
  weight numeric(14,3) not null check (weight >= 0),
  tare_weight numeric(14,3) not null default 0 check (tare_weight >= 0 and tare_weight <= weight),
  net_weight numeric(14,3) generated always as (weight - tare_weight) stored,
  unit text not null check (unit in ('kg', 'g', 'lb')),
  captured_at timestamptz not null default now(),
  image_path text not null,
  image_url text,
  image_public_id text,
  core_image_path text,
  core_image_url text,
  core_image_public_id text,
  qr_image_path text,
  qr_image_url text,
  qr_image_public_id text,
  device_id text references public.devices(id),
  gateway_id text,
  station_id text,
  camera_id text,
  analysis_id text,
  frame_sha256 text,
  qr_frame_sha256 text,
  payload_hash text,
  weight_source text not null default 'manual',
  qr_source text not null default 'unknown',
  weight_kind text not null default 'gross',
  error_status text not null default 'ok'
    check (error_status in ('ok', 'error')),
  error_reason text not null default '',
  status text not null default 'confirmed' check (status in ('confirmed', 'void')),
  confirmed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Upgrade the earlier prototype schema without destroying existing records.
alter table public.measurements
  add column if not exists device_id text references public.devices(id),
  add column if not exists tare_weight numeric(14,3) not null default 0,
  add column if not exists net_weight numeric(14,3) generated always as (weight - tare_weight) stored,
  add column if not exists image_url text,
  add column if not exists image_public_id text,
  add column if not exists core_image_path text,
  add column if not exists core_image_url text,
  add column if not exists core_image_public_id text,
  add column if not exists qr_image_path text,
  add column if not exists qr_image_url text,
  add column if not exists qr_image_public_id text,
  add column if not exists gateway_id text,
  add column if not exists station_id text,
  add column if not exists camera_id text,
  add column if not exists analysis_id text,
  add column if not exists frame_sha256 text,
  add column if not exists qr_frame_sha256 text,
  add column if not exists payload_hash text,
  add column if not exists weight_source text not null default 'manual',
  add column if not exists qr_source text not null default 'unknown',
  add column if not exists weight_kind text not null default 'gross',
  add column if not exists status text not null default 'confirmed',
  add column if not exists confirmed_at timestamptz not null default now(),
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

update public.measurements
set
  core_image_path = coalesce(core_image_path, image_path),
  core_image_url = coalesce(core_image_url, image_url),
  core_image_public_id = coalesce(core_image_public_id, image_public_id)
where core_image_path is null
   or core_image_url is null
   or core_image_public_id is null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.measurements'::regclass
      and conname = 'measurements_tare_weight_check'
  ) then
    alter table public.measurements
      add constraint measurements_tare_weight_check
      check (tare_weight >= 0 and tare_weight <= weight);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.measurements'::regclass
      and conname = 'measurements_status_check'
  ) then
    alter table public.measurements
      add constraint measurements_status_check
      check (status in ('confirmed', 'void'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.measurements'::regclass
      and conname = 'measurements_frame_sha256_check'
  ) then
    alter table public.measurements
      add constraint measurements_frame_sha256_check
      check (frame_sha256 is null or frame_sha256 ~* '^[0-9a-f]{64}$');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.measurements'::regclass
      and conname = 'measurements_payload_hash_check'
  ) then
    alter table public.measurements
      add constraint measurements_payload_hash_check
      check (payload_hash is null or payload_hash ~* '^[0-9a-f]{64}$');
  end if;
end $$;

create index if not exists measurements_qr_idx
  on public.measurements (qr_code);

create index if not exists measurements_captured_at_idx
  on public.measurements (captured_at desc);

create index if not exists measurements_device_idx
  on public.measurements (device_id, captured_at desc);

create index if not exists measurements_capture_identity_idx
  on public.measurements (gateway_id, station_id, camera_id, captured_at desc);

create index if not exists measurements_analysis_id_idx
  on public.measurements (analysis_id)
  where analysis_id is not null;

create index if not exists measurements_lookup_idx
  on public.measurements (qr_code, status, captured_at desc);

alter table public.devices enable row level security;
alter table public.rolls enable row level security;
alter table public.measurements enable row level security;

-- No anon/authenticated policies are created. Only the Edge Function's
-- service-role client can access these tables.
revoke all on table public.devices from anon, authenticated;
revoke all on table public.rolls from anon, authenticated;
revoke all on table public.measurements from anon, authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'roll-captures',
  'roll-captures',
  false,
  6291456,
  array['image/jpeg']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Main production table. Render Persistent Disk commits local evidence before
-- cloud sync; Supabase stores rows/metadata while Cloudinary serves images.
create table if not exists public.can_tu_dong (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  qr_code text not null,
  weight numeric(14,3) not null check (weight >= 0),
  tare_weight numeric(14,3) not null default 0
    check (tare_weight >= 0 and tare_weight <= weight),
  net_weight numeric(14,3) generated always as (weight - tare_weight) stored,
  unit text not null check (unit in ('kg', 'g', 'lb')),
  captured_at timestamptz not null default now(),
  image_path text not null,
  image_url text,
  image_public_id text,
  core_image_path text,
  core_image_url text,
  core_image_public_id text,
  qr_image_path text,
  qr_image_url text,
  qr_image_public_id text,
  device_id text references public.devices(id),
  gateway_id text,
  station_id text,
  camera_id text,
  analysis_id text,
  frame_sha256 text,
  qr_frame_sha256 text,
  payload_hash text,
  weight_source text not null default 'manual',
  qr_source text not null default 'unknown',
  weight_kind text not null default 'gross',
  error_status text not null default 'ok'
    check (error_status in ('ok', 'error')),
  error_reason text not null default '',
  status text not null default 'confirmed' check (status in ('confirmed', 'void')),
  confirmed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.can_tu_dong is
  'Automatic scale records. Render Persistent Disk commits image evidence before cloud sync; Cloudinary is delivery and may be released after 7 days. Supabase stores rows/metadata, not new image bytes.';
comment on column public.can_tu_dong.image_path is
  'Cloudinary public ID; legacy rows may contain a Supabase Storage path.';
comment on column public.can_tu_dong.image_url is
  'Cloudinary secure delivery URL.';
comment on column public.can_tu_dong.core_image_url is
  'Cloudinary delivery URL for the core-weight evidence image (ẢNH TL LÕI).';

-- Upgrade an existing production table without rewriting legacy rows.
alter table public.can_tu_dong
  add column if not exists core_image_path text,
  add column if not exists core_image_url text,
  add column if not exists core_image_public_id text,
  add column if not exists qr_image_path text,
  add column if not exists qr_image_url text,
  add column if not exists qr_image_public_id text,
  add column if not exists gateway_id text,
  add column if not exists station_id text,
  add column if not exists camera_id text,
  add column if not exists analysis_id text,
  add column if not exists frame_sha256 text,
  add column if not exists qr_frame_sha256 text,
  add column if not exists payload_hash text,
  add column if not exists error_status text not null default 'ok',
  add column if not exists error_reason text not null default '';

update public.can_tu_dong
set
  core_image_path = coalesce(core_image_path, image_path),
  core_image_url = coalesce(core_image_url, image_url),
  core_image_public_id = coalesce(core_image_public_id, image_public_id)
where core_image_path is null
   or core_image_url is null
   or core_image_public_id is null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.can_tu_dong'::regclass
      and conname = 'can_tu_dong_frame_sha256_check'
  ) then
    alter table public.can_tu_dong
      add constraint can_tu_dong_frame_sha256_check
      check (frame_sha256 is null or frame_sha256 ~* '^[0-9a-f]{64}$');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.can_tu_dong'::regclass
      and conname = 'can_tu_dong_payload_hash_check'
  ) then
    alter table public.can_tu_dong
      add constraint can_tu_dong_payload_hash_check
      check (payload_hash is null or payload_hash ~* '^[0-9a-f]{64}$');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.can_tu_dong'::regclass
      and conname = 'can_tu_dong_error_status_check'
  ) then
    alter table public.can_tu_dong
      add constraint can_tu_dong_error_status_check
      check (error_status in ('ok', 'error'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.can_tu_dong'::regclass
      and conname = 'can_tu_dong_error_reason_check'
  ) then
    alter table public.can_tu_dong
      add constraint can_tu_dong_error_reason_check
      check (
        (error_status = 'ok' and error_reason = '') or
        (error_status = 'error' and length(btrim(error_reason)) > 0)
      );
  end if;
end $$;

comment on column public.can_tu_dong.gateway_id is
  'Stable gateway/computer identity. device_id remains populated for compatibility.';
comment on column public.can_tu_dong.analysis_id is
  'Opaque ID for the local frame-analysis attempt that produced this event.';
comment on column public.can_tu_dong.frame_sha256 is
  'Lowercase SHA-256 of the exact JPEG bytes uploaded to Cloudinary.';
comment on column public.can_tu_dong.payload_hash is
  'Lowercase SHA-256 of the canonical immutable measurement payload.';

create index if not exists can_tu_dong_qr_idx
  on public.can_tu_dong (qr_code);
create index if not exists can_tu_dong_captured_at_idx
  on public.can_tu_dong (captured_at desc);
create index if not exists can_tu_dong_device_idx
  on public.can_tu_dong (device_id, captured_at desc);
create index if not exists can_tu_dong_capture_identity_idx
  on public.can_tu_dong (gateway_id, station_id, camera_id, captured_at desc);
create index if not exists can_tu_dong_analysis_id_idx
  on public.can_tu_dong (analysis_id)
  where analysis_id is not null;
create index if not exists can_tu_dong_lookup_idx
  on public.can_tu_dong (qr_code, status, captured_at desc);
create index if not exists can_tu_dong_image_public_id_idx
  on public.can_tu_dong (image_public_id)
  where image_public_id is not null;
create index if not exists can_tu_dong_core_image_public_id_idx
  on public.can_tu_dong (core_image_public_id)
  where core_image_public_id is not null;
create index if not exists can_tu_dong_qr_image_public_id_idx
  on public.can_tu_dong (qr_image_public_id)
  where qr_image_public_id is not null;

alter table public.can_tu_dong enable row level security;
revoke all on table public.can_tu_dong from anon, authenticated;

create table if not exists public.ca_can (
  id bigint generated by default as identity primary key,
  batch_key text not null unique,
  dot_can integer not null check (dot_can > 0),
  moc_so_luong integer not null check (moc_so_luong = dot_can * 10),
  ma_san_pham text not null,
  so_luong integer not null default 10 check (so_luong = 10),
  ngay_can date not null,
  gio_bat_dau timestamptz not null,
  gio_ket_thuc timestamptz not null,
  ca text not null,
  may text not null default '',
  lenh_san_xuat text not null,
  danh_sach_san_pham jsonb not null default '[]'::jsonb
    check (jsonb_typeof(danh_sach_san_pham) = 'array'),
  trang_thai text not null default 'confirmed'
    check (trang_thai in ('confirmed', 'void')),
  xac_nhan_boi text not null default '',
  xac_nhan_luc timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (ngay_can, ca, may, lenh_san_xuat, dot_can),
  check (gio_bat_dau <= gio_ket_thuc)
);

create index if not exists ca_can_source_idx
  on public.ca_can (ngay_can desc, ca, may, lenh_san_xuat, dot_can desc);

alter table public.ca_can enable row level security;
revoke all on table public.ca_can from anon, authenticated;

insert into public.can_tu_dong (
  id, event_id, qr_code, weight, tare_weight, unit, captured_at,
  image_path, image_url, image_public_id,
  core_image_path, core_image_url, core_image_public_id,
  qr_image_path, qr_image_url, qr_image_public_id,
  device_id, weight_source,
  gateway_id, station_id, camera_id, analysis_id, frame_sha256, qr_frame_sha256,
  payload_hash,
  qr_source, weight_kind, status, confirmed_at, metadata, created_at
)
overriding system value
select
  id, event_id, qr_code, weight, tare_weight, unit, captured_at,
  image_path, image_url, image_public_id,
  coalesce(core_image_path, image_path), coalesce(core_image_url, image_url),
  coalesce(core_image_public_id, image_public_id),
  qr_image_path, qr_image_url, qr_image_public_id, device_id, weight_source,
  gateway_id, station_id, camera_id, analysis_id, frame_sha256, qr_frame_sha256,
  payload_hash,
  qr_source, weight_kind, status, confirmed_at, metadata, created_at
from public.measurements
on conflict (event_id) do nothing;

select setval(
  pg_get_serial_sequence('public.can_tu_dong', 'id'),
  coalesce((select max(id) from public.can_tu_dong), 1),
  exists(select 1 from public.can_tu_dong)
);

-- Ảnh cân chờ AI is saved immediately without fabricated QR/weight values.
create table if not exists public.anh_can_cho_ai (
  id bigserial primary key,
  event_id uuid not null unique,
  parent_event_id uuid not null,
  capture_kind text not null default 'core'
    check (capture_kind in ('core', 'product', 'inventory')),
  capture_round integer not null default 0
    check (capture_round between 0 and 3),
  qr_code text,
  captured_at timestamptz not null,
  image_path text not null,
  image_url text,
  image_public_id text not null,
  gateway_id text not null,
  station_id text,
  camera_id text,
  frame_sha256 text,
  payload_hash text,
  qr_source text not null default 'none',
  work_date date,
  shift text,
  machine text,
  production_order text,
  status text not null default 'awaiting_ai'
    check (status in ('awaiting_ai', 'processing', 'processed', 'failed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists anh_can_cho_ai_status_time_idx
  on public.anh_can_cho_ai (status, captured_at);
create index if not exists anh_can_cho_ai_qr_idx
  on public.anh_can_cho_ai (qr_code)
  where qr_code is not null;
create index if not exists anh_can_cho_ai_parent_event_idx
  on public.anh_can_cho_ai (parent_event_id, capture_round, capture_kind);

alter table public.anh_can_cho_ai
  alter column image_url drop not null,
  alter column image_public_id drop not null;

alter table public.anh_can_cho_ai enable row level security;
revoke all on table public.anh_can_cho_ai from anon, authenticated;

-- Cân kiểm kho is a parallel, one-photo workflow. It intentionally does not
-- reuse can_tu_dong because the production slip still requires two images.
create table if not exists public.can_kiem_kho (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  ma_san_pham text not null check (char_length(ma_san_pham) between 1 and 512),
  khoi_luong numeric(14,3) not null check (khoi_luong >= 0),
  khoi_luong_loi numeric(14,3) not null default 0 check (khoi_luong_loi >= 0),
  khoi_luong_bi numeric(14,3) not null default 0 check (khoi_luong_bi >= 0),
  don_vi text not null default 'kg' check (don_vi in ('kg', 'g', 'lb')),
  captured_at timestamptz not null default now(),
  image_path text not null,
  image_url text,
  image_public_id text,
  gateway_id text,
  station_id text,
  camera_id text,
  analysis_id text,
  frame_sha256 text check (frame_sha256 is null or frame_sha256 ~* '^[0-9a-f]{64}$'),
  payload_hash text check (payload_hash is null or payload_hash ~* '^[0-9a-f]{64}$'),
  weight_source text not null default 'manual',
  qr_source text not null default 'unknown',
  status text not null default 'confirmed' check (status in ('confirmed', 'void')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.can_kiem_kho is
  'Cân kiểm kho: một ảnh, một lần đọc khối lượng; không có bước chụp cân lõi riêng.';
create index if not exists can_kiem_kho_ma_san_pham_idx
  on public.can_kiem_kho (ma_san_pham);
create index if not exists can_kiem_kho_captured_at_idx
  on public.can_kiem_kho (captured_at desc);
create index if not exists can_kiem_kho_station_time_idx
  on public.can_kiem_kho (gateway_id, station_id, camera_id, captured_at desc);
alter table public.can_kiem_kho enable row level security;
revoke all on table public.can_kiem_kho from anon, authenticated;
grant select on table public.can_kiem_kho to anon;
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'can_kiem_kho'
      and policyname = 'anon_read_can_kiem_kho'
  ) then
    create policy anon_read_can_kiem_kho
      on public.can_kiem_kho for select to anon using (true);
  end if;
end
$$;
