-- A confirmed/printable group for every 10 production weighing records.
-- Each individual record also carries the operator's quality/error result.

alter table public.can_tu_dong
  add column if not exists error_status text not null default 'ok',
  add column if not exists error_reason text not null default '';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.can_tu_dong'::regclass
      and conname = 'can_tu_dong_error_status_check'
  ) then
    alter table public.can_tu_dong
      add constraint can_tu_dong_error_status_check
      check (error_status in ('ok', 'error'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.can_tu_dong'::regclass
      and conname = 'can_tu_dong_error_reason_check'
  ) then
    alter table public.can_tu_dong
      add constraint can_tu_dong_error_reason_check
      check (
        (error_status = 'ok' and error_reason = '') or
        (error_status = 'error' and length(btrim(error_reason)) > 0)
      );
  end if;
end $$;

create table if not exists public.ca_can (
  id bigint generated by default as identity primary key,
  batch_key text not null unique,
  dot_can integer not null check (dot_can > 0),
  moc_so_luong integer not null check (moc_so_luong = dot_can * 10),
  ma_san_pham text not null,
  so_luong integer not null default 10 check (so_luong = 10),
  ngay_can date not null,
  gio_bat_dau timestamptz not null,
  gio_ket_thuc timestamptz not null,
  ca text not null,
  may text not null default '',
  lenh_san_xuat text not null,
  danh_sach_san_pham jsonb not null default '[]'::jsonb
    check (jsonb_typeof(danh_sach_san_pham) = 'array'),
  trang_thai text not null default 'confirmed'
    check (trang_thai in ('confirmed', 'void')),
  xac_nhan_boi text not null default '',
  xac_nhan_luc timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (ngay_can, ca, may, lenh_san_xuat, dot_can),
  check (gio_bat_dau <= gio_ket_thuc)
);

comment on table public.ca_can is
  'One confirmed and printable production weighing batch for each 10 rolls.';
comment on column public.ca_can.danh_sach_san_pham is
  'Ordered snapshot of the 10 can_tu_dong rows included in this batch.';

create index if not exists ca_can_source_idx
  on public.ca_can (ngay_can desc, ca, may, lenh_san_xuat, dot_can desc);

alter table public.ca_can enable row level security;
revoke all on table public.ca_can from anon, authenticated;
